name: esa_tf_platform
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - blosc
  - cloudpickle = 3.1.0
  - dask = 2024.9.1
  - flake8
  - gdal
  - hdf5
  - isort
  - lz4
  - nomkl
  - pip
  - pydantic<2
  - pytest
  - pytest-cov
  - python = 3.12
  - pip:
      - Authlib
      - cachetools
      - mdformat-gfm
      - sentinelsat
