name: esa_tf_restapi
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black
  - cloudpickle = 3.1.0
  - dask-core = 2024.9.1
  - distributed
  - fastapi = 0.97.0
  - flake8
  - gunicorn
  - isort
  - make
  - nomkl
  - pip
  - pytest
  - pytest-cov
  - python = 3.12
  - uvicorn
  - pip:
      - Authlib
      - mdformat-gfm
      - odata-query
      - sentinelsat
      - httpx
